# NumPy

In [1]:
import numpy as np

# 配列の作成

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print("arr:", arr)

arr: [1 2 3 4 5]


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("matrix:")
print(matrix)

matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 配列の基本的な操作

In [4]:
print("arr shape:", arr.shape)
print("arr ndim:", arr.ndim)
print("arr dtype:", arr.dtype)

arr shape: (5,)
arr ndim: 1
arr dtype: int32


# 基本的な演算

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result_sum = a + b
print("Sum of a and b:", result_sum)

result_multiply = a * b
print("Product of a and b:", result_multiply)

Sum of a and b: [5 7 9]
Product of a and b: [ 4 10 18]


# 行列の掛け算

In [6]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

result_matrix = np.dot(matrix_a, matrix_b)
print("Matrix multiplication result:")
print(result_matrix)

Matrix multiplication result:
[[19 22]
 [43 50]]


# インデクシングとスライシング

In [7]:
print("Element at index 2 in arr:", arr[2])
print("Slice of arr from index 1 to 4:", arr[1:4])

Element at index 2 in arr: 3
Slice of arr from index 1 to 4: [2 3 4]


# 統計関数

In [8]:
data = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(data)
print("Mean value of data:", mean_value)

std_dev = np.std(data)
print("Standard deviation of data:", std_dev)

max_value = np.max(data)
print("Maximum value in data:", max_value)

min_value = np.min(data)
print("Minimum value in data:", min_value)

Mean value of data: 3.0
Standard deviation of data: 1.4142135623730951
Maximum value in data: 5
Minimum value in data: 1
